"""A runnable, self-contained demonstration of finite-domain fADE discovery.

This script does *not* require any external download.  It synthesises a
"real-data-like" tracer-transport field on a bounded column --- a time-fractional
advection--dispersion process with an inflow boundary, sampled the way an X-ray
or sectioned-column experiment would sample concentration ``c(x, t)`` --- then
adds measurement noise and recovers the governing equation with the
finite-domain weak-Pareto configuration.

It serves two purposes: a smoke test that the real-data path runs end to end,
and a worked template to copy when a genuine field (see ``README.md``) is
available --- replace :func:`synthesise_column_field` with ``load_field_csv``
or ``load_field_npz`` and keep the rest.

The synthetic field is generated by an explicit finite-difference scheme using
one-sided Grunwald weights for the spatial dispersion and an L1 scheme for the
Caputo time derivative, i.e. the *forward* model of the operators the discovery
uses.  It is a stand-in for real data, clearly labelled as such; it is not one of
the paper's benchmarks and is not used for any reported result.

Run from the package root:

    PYTHONPATH=. python real_data/demo_synthetic_column.py
"""

from __future__ import annotations

import argparse
import warnings

import numpy as np

from real_data.real_fade import bounded_transport_config, discover, make_dataset


def _gl_weights(alpha: float, n: int) -> np.ndarray:
    """Grunwald weights g_k for a one-sided derivative of order ``alpha``."""
    g = np.empty(n)
    g[0] = 1.0
    for k in range(1, n):
        g[k] = g[k - 1] * (1.0 - (alpha + 1.0) / k)
    return g


def synthesise_column_field(
    n_t: int = 90,
    n_x: int = 80,
    L: float = 20.0,
    T: float = 8.0,
    alpha: float = 0.85,
    beta: float = 1.7,
    velocity: float = 1.0,
    dispersion: float = 0.25,
    seed: int = 0,
):
    """Forward-simulate a time-fractional advection--dispersion column.

        D_t^alpha c = -v * d_x c + D * d_x^beta c,    x in [0, L],

    with an inflow pulse at ``x = 0`` and an absorbing far end.  Returns
    ``(t, x, C_clean)``.  This is an illustrative stand-in for a real tracer
    field, not a paper benchmark.

    The spatial operators are taken from the package itself (one-sided Grunwald
    matrices), and the Caputo time derivative is advanced with the standard L1
    scheme, so the generated field is consistent with the operators the
    discovery searches over.
    """
    from math import gamma
    from fractional_weak_form import gl_matrix

    x = np.linspace(0.0, L, n_x)
    t = np.linspace(0.0, T, n_t)
    dx = x[1] - x[0]
    dt = t[1] - t[0]

    # spatial right-hand-side operator S_x = -v d_x + D d_x^beta (left/causal Grunwald)
    G1 = gl_matrix(n_x, 1.0, dx, side="left").toarray()
    Gb = gl_matrix(n_x, beta, dx, side="left").toarray()
    Sx = -velocity * G1 + dispersion * Gb

    # Caputo-L1 weights and lead coefficient
    b = np.array([(k + 1) ** (1.0 - alpha) - k ** (1.0 - alpha) for k in range(n_t)])
    l1 = dt ** (-alpha) / gamma(2.0 - alpha)

    C = np.zeros((n_t, n_x))
    inflow = np.exp(-((t - 1.2) ** 2) / (2 * 0.5**2))     # smooth injected pulse at x=0
    C[0, 0] = inflow[0]

    for n in range(1, n_t):
        # standard L1 history: c_n = sum_{k=1}^{n-1}(b_{k-1}-b_k) c_{n-k} + b_{n-1} c_0 + F/l1
        S = b[n - 1] * C[0]
        if n >= 2:
            coeff = b[:n - 1] - b[1:n]                      # (b_{k-1}-b_k), k=1..n-1
            S = S + coeff @ C[n - 1:0:-1]                   # c_{n-1}, c_{n-2}, ..., c_1
        F = C[n - 1] @ Sx.T                                 # explicit spatial RHS
        C[n] = S + F / l1
        C[n, 0] = inflow[n]                                 # inflow (Dirichlet) boundary
        C[n] = np.clip(C[n], 0.0, None)
    return t, x, C


def main() -> None:
    ap = argparse.ArgumentParser(description="Synthetic finite-domain fADE discovery demo.")
    ap.add_argument("--noise", type=float, default=3.0, help="measurement noise (percent)")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--budget", choices=["smoke", "standard", "paper"], default="standard")
    args = ap.parse_args()

    warnings.filterwarnings("ignore")
    print("Synthesising a real-data-like tracer column "
          "(time-fractional advection--dispersion, inflow boundary)...")
    t, x, C = synthesise_column_field(seed=args.seed)

    rng = np.random.default_rng(args.seed)
    C_noisy = C * (1.0 + (args.noise / 100.0) * rng.uniform(-1.0, 1.0, size=C.shape))
    data = make_dataset(t, x, C_noisy, name="synthetic_tracer_column")

    print(f"Field shape (n_t, n_x) = {C.shape}; injected noise = {args.noise:.1f}%.")
    print("True (synthesised) law:  D_t^0.85 c = -1.0 d_x c + 0.25 d_x^1.7 c  (left/causal operators).\n")

    config = bounded_transport_config(
        time_fractional=True, space_side="left",
        alpha_range=(0.5, 1.1), beta_range=(0.7, 2.0),
        p_values=(0, 1), seed=args.seed, maxiter=30, popsize=10,
    )
    discover(data, config, test_budget=args.budget, verbose=True)

    print("\nNote: this is a wiring template, not a benchmark.  An advection-dominated,")
    print("sharp-front, bounded-domain field is a genuinely hard identification problem,")
    print("so the recovered orders are estimates; identifiability of fractional orders is")
    print("discussed in Section 5 of the paper.  For your own data, tune the search ranges,")
    print("budget, regularisation (lam_t/lam_x), and space_side to the physics.")

    print("\nTo use real data instead, replace synthesise_column_field(...) with")
    print("  data = load_field_csv('your_column.csv')   # or load_field_npz / regrid_scattered")
    print("and keep the bounded_transport_config(...) call (adjust space_side / ranges to the physics).")


if __name__ == "__main__":
    main()
